### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by AgostinoSturaro** [jahnf/strawberry-ini#1]
This library seems to be one of the most promising on GitHub, quality-wise.
Starred it :)
Is it safe to use in a production environment?

If so, [downloadable release](https://help.github.com/articles/creating-releases/) would be nice.

BWT does it have documentation hosted somewhere?

**Comment by jahnf** [comment]
Hello , thanks for your interest in the library
I can say that the library is very stable and can be used in production. Depending on the use case and scenario it is a good idea to add (integration) tests to the existing unit tests.

I'll see to making a release available within the next week. Currently documentation is not online somewhere but can be generated with doxygen .. or the make doc target when building with cmake. 

The example should show the basic usage but more detailed examples are missing (usage without using the heap, without a dictionary...) and details about the options/defines that can be used at compile time are also only described in the header.

**Comment by jahnf** [comment]
Release tagged.
https://github.com/jahnf/strawberry-ini/releases
